[metadata]
version = "1.0"

[versions]
asm = "9.10.1"
checkstyle = "12.3.1"
indra = "4.1.0"
tinylog = "2.7.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.1.0" }

# logger
tinylog-api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }

# loader
accessWidener = { module = "net.fabricmc:access-widener", version = "2.1.0" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
mixin = { module = "net.fabricmc:sponge-mixin", version = "0.17.3+mixin.0.8.7" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version = "0.5.4" }
gson = { module = "com.google.code.gson:gson", version = "2.14.0" }

# build
stylecheck = "ca.stellardrift:stylecheck:0.2.1"

build-indra = { module = "net.kyori:indra-common", version.ref = "indra" }
build-indra-sonatype = { module = "net.kyori:indra-publishing-sonatype", version.ref = "indra" }
build-indra-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
build-shadow = { module = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin", version = "9.5.1" }

# unused, for renovate
zCheckstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

[plugins]
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
