name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3
      - name: "setup jdk 11"
        uses: actions/setup-java@v3
        with:
          java-version: "11"
      - name: "build"
        run: "./gradlew build"
      - name: "publish"
        if: ${{ runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: "./gradlew publish"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
